---
title: "Prediction assessment of POC values from best plankton predictors"
author: "Thelma Panaïotis"
format:
  html:
    toc: true
    embed-resources: true
editor: visual
execute:
  cache: true
  warning: false
---

## Set-up and load data

```{r set-up}
#|output: false
#|cache: false
source("utils.R")
load("data/13.poc_from_plankton_richness_fit.Rdata")
```

## Rsquares

Black dots on the R² boxplots show the actual values.

```{r rsq}
#| fig-column: body-outset
#| out-width: 100%

preds <- res %>%
  select(predictor_set, cv_type, fold, preds) %>%
  unnest(preds)

rsquares <- preds %>%
  group_by(predictor_set, cv_type, fold) %>%
  rsq(truth = poc_log, estimate = .pred) %>%
  mutate(predictor_set = forcats::fct_reorder(predictor_set, .estimate, .desc = TRUE))

ggplot(rsquares) +
  geom_boxplot(aes(x = predictor_set, y = .estimate, colour = cv_type)) +
  geom_jitter(aes(x = predictor_set, y = .estimate, colour = cv_type), size = 0.5, position = position_jitterdodge(dodge.width = 0.75, jitter.width = 0.3)) +
  scale_y_continuous(limits = c(0, 1), expand = c(0, 0)) +
  labs(x = "Predictor set", y = "R²", colour = "CV type") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

## 
